apiVersion: v1
kind: Service
metadata:
  name: portfolio
spec:
  type: NodePort
  selector:
    app: portfolio
  ports:
    - port: 3050
      protocol: TCP
      targetPort: 3000
      nodePort: 31000